### PR TITLE
Add Gitlab OAuth as standard provider

### PR DESCRIPTION
**Pull request by Iamsidar07**
This PR add Gitlab OAuth as standard provider.

### CODE REVIEW

**Comment by fomalhautb** [comment]
Thanks for contributing!

**Comment by Iamsidar07** [comment]
> Thanks for contributing!

I’m considering adding more OAuth providers, such as Twitter, LinkedIn, and Bitbucket. Do you think these would be valuable additions?

**Comment by fomalhautb** [comment]
> > Thanks for contributing!
> 
> I’m considering adding more OAuth providers, such as Twitter, LinkedIn, and Bitbucket. Do you think these would be valuable additions? And discord link is broken.

Of course, that would be amazing!
Which discord link?

**Comment by Iamsidar07** [comment]
> > > Thanks for contributing!
> > 
> > I’m considering adding more OAuth providers, such as Twitter, LinkedIn, and Bitbucket. Do you think these would be valuable additions? And discord link is broken.
> 
> Of course, that would be amazing!
> Which discord link?

Sorry! It is working now!

**Comment by Iamsidar07** [comment]
@fomalhautb, I've added a few more OAuth providers. Could you please review PRs #206 and #207?

**Pull request merged**
