### PR TITLE
feat: Add twitter oauth provider

### PR DESCRIPTION
**Pull request by Iamsidar07**
This PR adds slack and twitter oauth provider.

### CODE REVIEW

**Comment by fomalhautb** [comment]
Hey this looks awesome! I need some time to register developer accounts on these platforms and test these providers. 

One thing that would be nice if you can do is to check if the providers provide email verification, if yes, read it from the provider. (We newly introduced it here, https://github.com/stack-auth/stack/pull/209, some examples:

https://github.com/stack-auth/stack/blob/41afba826474d8a711bdb5b4d325d0a035d9521d/apps/backend/src/oauth/providers/facebook.tsx#L46-L50

https://github.com/stack-auth/stack/blob/41afba826474d8a711bdb5b4d325d0a035d9521d/apps/backend/src/oauth/providers/discord.tsx#L38

**Comment by Iamsidar07** [comment]
I will do it!

**Comment by fomalhautb** [comment]
Did you tested twitter? It doesn't seem to work for me, I get 404 after clicking on the login button.

**Comment by Iamsidar07** [comment]
> Did you test twitter? It doesn't seem to work for me, I get 404 after clicking on the login button.

I tested in postman, I will look into it.

**Comment by Iamsidar07** [comment]
> Did you test twitter? It doesn't seem to work for me, I get 404 after clicking on the login button.

@fomalhautb  I think it is working fine for me. I am using Oauth2.0. Here is some screenshot.  I have to do some fixes in PR #207. I will let you know when I am done.
Screenshot from 2024-08-29 06-25-32
Screenshot from 2024-08-29 06-27-24
Screenshot from 2024-08-29 06-25-59
Screenshot from 2024-08-29 06-25-41

**Comment by fomalhautb** [comment]
Can you maybe make sure that it works with client? To test it locally, you can create an account on the dashboard, edit the projectUser table to add `{ managedProjectIds: ["internal"] }` to the `serverMetadata`, then you can add twitter/slack keys to the auth method, log out, and test those login methods

**Comment by fomalhautb** [comment]
I will make this PR only Twitter and later add Slack in a different PR.

**Pull request merged**
