### PR TITLE
Updated text and background colors to ensure consistency across Light mode and Dark Mode

### PR DESCRIPTION
**Pull request by RahulMishra0722**
### 1 Before as you can see in the image in dark mode when you typed out you email it wasnt visible you would have to double click highlight to see*

Screenshot 2024-06-15 at 8 10 46 PM

### Both Light and Dark Mode
Screenshot 2024-06-17 at 2 36 16 AM

Screenshot 2024-06-17 at 2 36 16 AM

### 2 If you saw the password and magic link toggle the colors were miss matched 
Before 
Screenshot 2024-06-16 at 4 21 51 PM
Screenshot 2024-06-15 at 8 10 38 PM

### After

Screenshot 2024-06-17 at 2 04 49 AM

Screenshot 2024-06-16 at 6 50 57 PM

### Final images in both dark and light mode for review
Screenshot 2024-06-17 at 2 36 49 AM

Screenshot 2024-06-17 at 2 36 40 AM
Screenshot 2024-06-17 at 2 36 30 AM
Screenshot 2024-06-17 at 2 36 16 AM

### CODE REVIEW

**Comment by RahulMishra0722** [comment]
i have signed this 
Screenshot 2024-06-17 at 2 53 15 AM

**Comment by fomalhautb** [comment]
Hey do you have the code to reproduce the original problem? I think the reason that you get the problem is because you have the dark theme from tailwind/default next.js but didn't set the class vars on html. 

We actually already have code handling the dark theme in these files [theme-provider.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/providers/theme-provider.tsx) and [browser-script.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/utils/browser-script.tsx). You can also check out the [color mode docs](https://docs.stack-auth.com/customization/custom-colors) for more information.

**Comment by RahulMishra0722** [comment]
> Hey do you have the code to reproduce the original problem? I think the reason that you get the problem is because you have the dark theme from tailwind/default next.js but didn't set the class vars on html.
> 
> We actually already have code handling the dark theme in these files [theme-provider.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/providers/theme-provider.tsx) and [browser-script.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/utils/browser-script.tsx). You can also check out the [color mode docs](https://docs.stack-auth.com/customization/custom-colors) for more information.

**i was confused to because i saw that you guys have the dark mode and light mode option and wasnt sure why it was happening i dont think i did "didn't set the class vars on html." this i cloned the repo and i was looking to solve the password miss match error on safari but saw this and thought solving this might be more helpfull also i came across this by following the guied that you guys have i created a next project and got the credentials /api for auth from the stack **
Screenshot 2024-06-17 at 6 16 55 PM
**
after putting the keys on .env.local i got to the auth page and saw when i typed my email i didnt see anything **
Screenshot 2024-06-17 at 6 19 37 PM 
**
**so i double clicked and saw **
Screenshot 2024-06-17 at 6 19 31 PM

**Comment by fomalhautb** [comment]
> > Hey do you have the code to reproduce the original problem? I think the reason that you get the problem is because you have the dark theme from tailwind/default next.js but didn't set the class vars on html.
> > We actually already have code handling the dark theme in these files [theme-provider.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/providers/theme-provider.tsx) and [browser-script.tsx](https://github.com/stack-auth/stack/blob/dev/packages/stack/src/utils/browser-script.tsx). You can also check out the [color mode docs](https://docs.stack-auth.com/customization/custom-colors) for more information.
> 
> **I was confused to because i saw that you guys have the dark mode and light mode option and wasnt sure why it was happening i dont think i did "didn't set the class vars on html." this i cloned the repo and i was looking to solve the password miss match error on safari but saw this and thought solving this might be more helpfull also i came across this by following the guide that you guys have, i created a next project and got the credentials /api for auth from the stack** Screenshot 2024-06-17 at 6 16 55 PM
> 
> **after putting the keys on .env.local i got to the auth page and saw when i typed my email i didnt see anything** Screenshot 2024-06-17 at 6 19 37 PM
> 
> **so i double clicked and saw** Screenshot 2024-06-17 at 6 19 31 PM

That makes sense, it is indeed confusing in the case you described. We will find a way to make it more intuitive for developers

**Pull request closed without merging**
