### PR TITLE
Added clientMetadata and serverMetadata in JSON values format

### LINKED ISSUE #69: Show & edit server/client metadata in the dashboard
In the users table, when clicking on the three dots and "edit", there should be fields for clientMetadata and serverMetadata that should accept JSON values

### PR DESCRIPTION
**Pull request by ManvendraPSdev**
Fixes #69

### CODE REVIEW

**Comment by narasimha-1511** [comment]
hey @ManvendraPSdev  

i think you have blindly copied code from harkirats youtube video ?

**Comment by ManvendraPSdev** [comment]
This is my first contribution to open source, and I am eager to make a positive and original impact. I believe this can be a great start to building momentum for my future contributions. Additionally, I am looking for more "good first issues" in this organization to further contribute.

**Comment by ManvendraPSdev** [comment]
Upon further reflection, I realized that my recent contribution closely resembles content from Harkirat's YouTube video. As a member of his 100xdev cohort, I initially thought following his example would be appropriate, but I understand now the importance of originality in open-source contributions.

**Comment by ManvendraPSdev** [comment]
hey @narasimha-1511 

I have not blindly copied the code , I invested my time in understanding the code 
, I am a beginner and this is my first open source contribution 
So I have just take the refrence from his video

**Comment by narasimha-1511** [comment]
@ManvendraPSdev Understood but don't raise duplicate PR s like these close this PR Yourself 😄

**Review by Alchemist1411 — CHANGES_REQUESTED** [review]
Why change the schema.prisma file ?
You shouldn't change that.

**Comment by N2D4** [comment]
Duplicate of #87

**Comment by ManvendraPSdev** [comment]
@CLAassistant  
I have to seed the database so It could be done either by creating the .env file  but since there is the error that it is unable to find the env variable therefore I have directly use the postgres credentials into the database , I can do it by defining the .env file also , Kindly tell me What should I do

**Pull request closed without merging**
