### PR TITLE
Add Gitlab OAuth Provider Integration

### PR DESCRIPTION
**Pull request by Iamsidar07**
This PR introduces the integration of Gitlab as an OAuth Provider.

### CODE REVIEW

**Comment by fomalhautb** [comment]
There are some more things you need to do to add a new provider, for example the frontend buttons. Also notice that GitLab should not be a new shared/proxied provider, but only as a standard provider. Here is an example of how to add discord

**Comment by Iamsidar07** [comment]
> There are some more things you need to do to add a new provider, for example the frontend buttons. Also notice that GitLab should not be a new shared/proxied provider, but only as a standard provider. Here is an example of how to add discord. ALso please make sure all the typechecks, lints, and tests pass

Can you share an example of how to add discord?

**Comment by fomalhautb** [comment]
> > There are some more things you need to do to add a new provider, for example the frontend buttons. Also notice that GitLab should not be a new shared/proxied provider, but only as a standard provider. Here is an example of how to add discord. ALso please make sure all the typechecks, lints, and tests pass
> 
> Can you share an example of how to add discord? Do I have to add oauth in both backend and dashboard?

Sorry, forgot to link it, https://github.com/stack-auth/stack/pull/187

**Comment by Iamsidar07** [comment]
> > > There are some more things you need to do to add a new provider, for example the frontend buttons. Also notice that GitLab should not be a new shared/proxied provider, but only as a standard provider. Here is an example of how to add discord. ALso please make sure all the typechecks, lints, and tests pass
> > 
> > 
> > Can you share an example of how to add discord? Do I have to add oauth in both backend and dashboard?
> 
> Sorry, forgot to link it, #187

Implemented in new PR #201, Please can you check it now? And thanks!

**Pull request closed without merging**
